import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";
import { noComments } from "./no-comments";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
    languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
});

ruleTester.run("no-comments", noComments, {
    valid: [
        {
            name: "code carrying no comments",
            code: `export const total = (values: number[]) => values.length;`,
        },
        {
            name: "a string that merely looks like a comment",
            code: `export const protocol = "https://example.com";`,
        },
        {
            name: "a comment matched by the allow option",
            code: `/* @generated by pnpm contract */\nexport const routes = {};`,
            options: [{ allow: ["@generated"] }],
        },
    ],
    invalid: [
        {
            name: "a leading line comment on its own line",
            code: `// Example: replace with your domain types\nexport type Trend = "up" | "down";`,
            output: `export type Trend = "up" | "down";`,
            errors: [{ messageId: "comment" }],
        },
        {
            name: "a trailing comment beside code",
            code: `const month = 1; // 0-based index`,
            output: `const month = 1; `,
            errors: [{ messageId: "comment" }],
        },
        {
            name: "an indented block comment inside a function",
            code: `function load() {\n    /* silently ignore */\n    return null;\n}`,
            output: `function load() {\n    return null;\n}`,
            errors: [{ messageId: "comment" }],
        },
        {
            name: "a jsx comment container",
            filename: "components/common/box.tsx",
            code: `export const Box = () => (\n    <div>\n        {/* Custom checkbox */}\n        <span />\n    </div>\n);`,
            output: `export const Box = () => (\n    <div>\n        <span />\n    </div>\n);`,
            errors: [{ messageId: "comment" }],
        },
        {
            name: "a jsdoc block and a line comment stacked together",
            code: `/** Does nothing. */\n// kept from the old implementation\nexport const noop = () => undefined;`,
            output: [
                `// kept from the old implementation\nexport const noop = () => undefined;`,
                `export const noop = () => undefined;`,
            ],
            errors: [{ messageId: "comment" }, { messageId: "comment" }],
        },
        {
            name: "a comment left unmatched by the allow option",
            code: `// TODO: revisit\nexport const noop = () => undefined;`,
            options: [{ allow: ["@generated"] }],
            output: `export const noop = () => undefined;`,
            errors: [{ messageId: "comment" }],
        },
    ],
});
