/* @generated by pnpm contract - edit the Nest DTOs instead */
export const routes = {
    appGetHello: () => "/api",
    authRegister: () => "/api/auth/register",
    authLogin: () => "/api/auth/login",
    authForgotPassword: () => "/api/auth/forgot-password",
    authResetPassword: () => "/api/auth/reset-password",
    authOnboarding: () => "/api/auth/onboarding",
    usersCreate: () => "/api/users",
    usersFindAll: () => "/api/users",
    usersGetMe: () => "/api/users/me",
    usersFindOne: (id: string) => `/api/users/${id}`,
    usersUpdate: (id: string) => `/api/users/${id}`,
    usersRemove: (id: string) => `/api/users/${id}`,
} as const;
