/* @generated by pnpm contract - edit the Nest DTOs instead */
import type { Endpoint } from "@/lib/types/api";
import type {
    AuthResponseDto,
    HealthResponseDto,
    PeriodSeriesResponseDto,
    PeriodTotalResponseDto,
    UserResponseDto,
} from "./schemas";

export const routes = {
    authRegister: () => "/api/auth/register" as Endpoint<AuthResponseDto>,
    authLogin: () => "/api/auth/login" as Endpoint<AuthResponseDto>,
    usersCreate: () => "/api/users" as Endpoint<UserResponseDto>,
    usersFindAll: () => "/api/users" as Endpoint<UserResponseDto[]>,
    usersGetMe: () => "/api/users/me" as Endpoint<UserResponseDto>,
    usersFindOne: (id: string) =>
        `/api/users/${id}` as Endpoint<UserResponseDto>,
    usersUpdate: (id: string) =>
        `/api/users/${id}` as Endpoint<UserResponseDto>,
    usersRemove: (id: string) =>
        `/api/users/${id}` as Endpoint<UserResponseDto>,
    healthCheck: () => "/api/health" as Endpoint<HealthResponseDto>,
    statsUsersTotal: () =>
        "/api/stats/users/total" as Endpoint<PeriodTotalResponseDto>,
    statsUsersSeries: () =>
        "/api/stats/users/series" as Endpoint<PeriodSeriesResponseDto>,
} as const;
