/* @generated by pnpm contract - edit the Nest DTOs instead */
import type { Endpoint } from "@/lib/types/api";
import type {
    AuthResponseDto,
    MessageResponseDto,
    UserResponseDto,
} from "./schemas";

export const routes = {
    appGetHello: () => "/api" as Endpoint<unknown>,
    authRegister: () => "/api/auth/register" as Endpoint<AuthResponseDto>,
    authLogin: () => "/api/auth/login" as Endpoint<AuthResponseDto>,
    authForgotPassword: () =>
        "/api/auth/forgot-password" as Endpoint<MessageResponseDto>,
    authResetPassword: () =>
        "/api/auth/reset-password" as Endpoint<MessageResponseDto>,
    authOnboarding: () =>
        "/api/auth/onboarding" as Endpoint<MessageResponseDto>,
    usersCreate: () => "/api/users" as Endpoint<UserResponseDto>,
    usersFindAll: () => "/api/users" as Endpoint<UserResponseDto[]>,
    usersGetMe: () => "/api/users/me" as Endpoint<UserResponseDto>,
    usersFindOne: (id: string) =>
        `/api/users/${id}` as Endpoint<UserResponseDto>,
    usersUpdate: (id: string) =>
        `/api/users/${id}` as Endpoint<UserResponseDto>,
    usersRemove: (id: string) =>
        `/api/users/${id}` as Endpoint<UserResponseDto>,
} as const;
