/* @generated by pnpm contract - edit the Nest DTOs instead */
import { z } from "zod";

export const registerDtoSchema = z.object({
    fullName: z.string(),
    email: z.string(),
    password: z.string(),
    role: z.enum(["ADMIN", "USER"]).optional(),
    phoneNumber: z.string().optional(),
});
export type RegisterDto = z.infer<typeof registerDtoSchema>;

export const loginDtoSchema = z.object({
    email: z.string(),
    password: z.string(),
});
export type LoginDto = z.infer<typeof loginDtoSchema>;

export const forgotPasswordDtoSchema = z.object({ email: z.string() });
export type ForgotPasswordDto = z.infer<typeof forgotPasswordDtoSchema>;

export const resetPasswordDtoSchema = z.object({
    password: z.string(),
    token: z.string(),
});
export type ResetPasswordDto = z.infer<typeof resetPasswordDtoSchema>;

export const onboardingDtoSchema = z.object({
    phoneNumber: z.string().optional(),
    bio: z.string().optional(),
});
export type OnboardingDto = z.infer<typeof onboardingDtoSchema>;

export const createUserDtoSchema = z.object({
    fullName: z.string(),
    email: z.string(),
    password: z.string(),
    role: z.enum(["ADMIN", "USER"]).optional(),
    phoneNumber: z.string().optional(),
    bio: z.string().optional(),
});
export type CreateUserDto = z.infer<typeof createUserDtoSchema>;

export const updateUserDtoSchema = z.object({
    fullName: z.string().optional(),
    email: z.string().optional(),
    password: z.string().optional(),
    role: z.enum(["ADMIN", "USER"]).optional(),
    phoneNumber: z.string().optional(),
    bio: z.string().optional(),
    status: z.enum(["ACTIVE", "PENDING", "SUSPENDED"]).optional(),
});
export type UpdateUserDto = z.infer<typeof updateUserDtoSchema>;
