/* @generated by pnpm contract - edit the Nest DTOs instead */
import { z } from "zod";

export const apiEnvelopeDtoSchema = z.object({
    statusCode: z.number(),
    message: z.string(),
    timestamp: z.string(),
});
export type ApiEnvelopeDto = z.infer<typeof apiEnvelopeDtoSchema>;

export const authResponseUserDtoSchema = z.object({
    id: z.string(),
    name: z.string(),
    email: z.string(),
    role: z.string(),
});
export type AuthResponseUserDto = z.infer<typeof authResponseUserDtoSchema>;

export const authResponseDtoSchema = z.object({
    user: authResponseUserDtoSchema,
    accessToken: z.string().optional(),
});
export type AuthResponseDto = z.infer<typeof authResponseDtoSchema>;

export const registerDtoSchema = z.object({
    fullName: z.string(),
    email: z.string(),
    password: z.string(),
    phoneNumber: z.string().optional(),
});
export type RegisterDto = z.infer<typeof registerDtoSchema>;

export const loginDtoSchema = z.object({
    email: z.string(),
    password: z.string(),
});
export type LoginDto = z.infer<typeof loginDtoSchema>;

export const userResponseDtoSchema = z.object({
    id: z.string(),
    fullName: z.string(),
    email: z.string(),
    phoneNumber: z.string().nullable(),
    avatar: z.string().nullable(),
    bio: z.string().nullable(),
    role: z.enum(["ADMIN", "USER"]),
    status: z.enum(["ACTIVE", "PENDING", "SUSPENDED"]),
    createdAt: z.string(),
    updatedAt: z.string(),
    lastActive: z.string().nullable(),
});
export type UserResponseDto = z.infer<typeof userResponseDtoSchema>;

export const createUserDtoSchema = z.object({
    fullName: z.string(),
    email: z.string(),
    password: z.string(),
    role: z.enum(["ADMIN", "USER"]).optional(),
    phoneNumber: z.string().optional(),
    bio: z.string().optional(),
});
export type CreateUserDto = z.infer<typeof createUserDtoSchema>;

export const updateUserDtoSchema = z.object({
    fullName: z.string().optional(),
    email: z.string().optional(),
    password: z.string().optional(),
    role: z.enum(["ADMIN", "USER"]).optional(),
    phoneNumber: z.string().optional(),
    bio: z.string().optional(),
    status: z.enum(["ACTIVE", "PENDING", "SUSPENDED"]).optional(),
});
export type UpdateUserDto = z.infer<typeof updateUserDtoSchema>;

export const healthResponseDtoSchema = z.object({ status: z.enum(["ok"]) });
export type HealthResponseDto = z.infer<typeof healthResponseDtoSchema>;

export const periodTotalResponseDtoSchema = z.object({
    period: z.enum(["day", "month", "year"]),
    start: z.string(),
    end: z.string(),
    total: z.number(),
});
export type PeriodTotalResponseDto = z.infer<
    typeof periodTotalResponseDtoSchema
>;

export const seriesPointDtoSchema = z.object({
    key: z.string(),
    value: z.number(),
});
export type SeriesPointDto = z.infer<typeof seriesPointDtoSchema>;

export const periodSeriesResponseDtoSchema = z.object({
    period: z.enum(["day", "month", "year"]),
    start: z.string(),
    end: z.string(),
    points: z.array(seriesPointDtoSchema),
});
export type PeriodSeriesResponseDto = z.infer<
    typeof periodSeriesResponseDtoSchema
>;
