export enum ActionType {
    WIN = "WIN",
    RATE = "RATE",
    LOGIN = "LOGIN",
    CREATE = "CREATE",
    REFUND = "REFUND",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
    LOGOUT = "LOGOUT",
    SUBMIT = "SUBMIT",
    REJECT = "REJECT",
    CREDIT = "CREDIT",
    ARCHIVE = "ARCHIVE",
    PUBLISH = "PUBLISH",
    SUSPEND = "SUSPEND",
    DEPOSIT = "DEPOSIT",
    APPROVE = "APPROVE",
    CERTIFY = "CERTIFY",
    FEEDBACK = "FEEDBACK",
    WITHDRAW = "WITHDRAW",
    ACTIVATE = "ACTIVATE",
    ASSIGN_ROLE = "ASSIGN_ROLE",
}

export enum ContestStatus {
    DRAFT = "DRAFT",
    ACTIVE = "ACTIVE",
    UPCOMING = "UPCOMING",
    COMPLETED = "COMPLETED",
}

export enum Day {
    SUN = "SUN",
    MON = "MON",
    TUE = "TUE",
    WED = "WED",
    THU = "THU",
    FRI = "FRI",
    SAT = "SAT",
}

export enum EntityType {
    QUIZ = "QUIZ",
    CHAT = "CHAT",
    USER = "USER",
    BADGE = "BADGE",
    ENTRY = "ENTRY",
    JUDGE = "JUDGE",
    SCHOOL = "SCHOOL",
    WALLET = "WALLET",
    MENTOR = "MENTOR",
    CONTEST = "CONTEST",
    SESSION = "SESSION",
    GUARDIAN = "GUARDIAN",
    TIMELINE = "TIMELINE",
    TRANSACTION = "TRANSACTION",
    NOTIFICATION = "NOTIFICATION",
    MENTOR_SESSIONS = "MENTOR_SESSIONS",
}

export enum EntryCategory {
    STEM = "STEM",
    FILM = "FILM",
    MUSIC = "MUSIC",
    WRITING = "WRITING",
    ANIMATION = "ANIMATION",
    GAME_DESIGN = "GAME_DESIGN",
    VISUAL_ARTS = "VISUAL_ARTS",
    PHOTOGRAPHY = "PHOTOGRAPHY",
    PERFORMING_ARTS = "PERFORMING_ARTS",
}

export enum EntryStatus {
    LIVE = "LIVE",
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    UNLISTED = "UNLISTED",
}

export enum Level {
    JSS1 = "JSS1",
    JSS2 = "JSS2",
    JSS3 = "JSS3",
    SSS1 = "SSS1",
    SSS2 = "SSS2",
    SSS3 = "SSS3",
}

export enum MentorAccountStatus {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    INACTIVE = "INACTIVE",
    PENDING_SETUP = "PENDING_SETUP",
}

export enum MentorSpecialty {
    STEM = "STEM",
    FILM = "FILM",
    MUSIC = "MUSIC",
    WRITING = "WRITING",
    ANIMATION = "ANIMATION",
    GAME_DESIGN = "GAME_DESIGN",
    VISUAL_ARTS = "VISUAL_ARTS",
    PHOTOGRAPHY = "PHOTOGRAPHY",
    PERFORMING_ARTS = "PERFORMING_ARTS",
}

export enum Month {
    JAN = "JAN",
    FEB = "FEB",
    MAR = "MAR",
    APR = "APR",
    MAY = "MAY",
    JUN = "JUN",
    JUL = "JUL",
    AUG = "AUG",
    SEP = "SEP",
    OCT = "OCT",
    NOV = "NOV",
    DEC = "DEC",
}

export enum NotificationTag {
    FEST = "FEST",
    OTHER = "OTHER",
    RESULT = "RESULT",
    SCHOOL = "SCHOOL",
    MENTOR = "MENTOR",
    GENERAL = "GENERAL",
    CONTEST = "CONTEST",
    DEADLINE = "DEADLINE",
    FINANCIAL = "FINANCIAL",
    SUBMISSION = "SUBMISSION",
}

export enum NotificationCategory {
    MODERATION = "MODERATION",
    JUDGES_LATE = "JUDGES_LATE",
    NEW_ENTRIES = "NEW_ENTRIES",
    PAYMENT_DELAY = "PAYMENT_DELAY",
    MONTHLY_REPORT = "MONTHLY_REPORT",
    RECONCILIATION = "RECONCILIATION",
    PAYMENT_DISPUTE = "PAYMENT_DISPUTE",
    UNUSUAL_ACTIVITY = "UNUSUAL_ACTIVITY",
    REPORT_SUBMISSION = "REPORT_SUBMISSION",
    PENDING_WITHDRAWAL = "PENDING_WITHDRAWAL",
    WITHDRAWAL_REQUEST = "WITHDRAWAL_REQUEST",
    HIGH_PRIORITY_FLAGGED = "HIGH_PRIORITY_FLAGGED",
    MARKETING_ASSETS_REQUIRED = "MARKETING_ASSETS_REQUIRED",
    CONTEST_SUBMISSION_DEADLINE = "CONTEST_SUBMISSION_DEADLINE",
    SCHOOL_VERIFICATION_PENDING = "SCHOOL_VERIFICATION_PENDING",
}

export enum SessionStatus {
    ACTIVE = "ACTIVE",
    FLAGGED = "FLAGGED",
    UPCOMING = "UPCOMING",
    CANCELLED = "CANCELLED",
    COMPLETED = "COMPLETED",
}

export enum TimeFilter {
    DAY = "day",
    YEAR = "year",
    MONTH = "month",
}

export enum TransactionAction {
    REFUND = "REFUND",
    DEPOSIT = "DEPOSIT",
    WITHDRAWAL = "WITHDRAWAL",
}

export enum TransactionStatus {
    FAILED = "FAILED",
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    AWAITING_REVIEW = "AWAITING_REVIEW",
    AWAITING_PARENT_APPROVAL = "AWAITING_PARENT_APPROVAL",
}

export enum UserAccountStatus {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    SUSPENDED = "SUSPENDED",
}

export enum SchoolStatus {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    INACTIVE = "INACTIVE",
    PLAYWORK_CERTIFIED = "PLAYWORK_CERTIFIED",
    PENDING_CERTIFICATION = "PENDING_CERTIFICATION",
}

/**
 *  ARTIST = "ARTIST",
    CREATOR = "CREATOR",
    BUILDER = "BUILDER",
    DIRECTOR = "DIRECTOR",
    VISIONARY = "VISIONARY",
 */
