

export enum SchoolStatus {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    INACTIVE = "INACTIVE",
    PLAYWORK_CERTIFIED = "PLAYWORK_CERTIFIED",
    PENDING_CERTIFICATION = "PENDING_CERTIFICATION",
}
