import {
    JsonSchema,
    OpenApiDocument,
    Operation,
    Parameter,
} from "./openapi-document";
import {
    orderByDependency,
    referencedSchemas,
    schemaConstName,
    typeExpression,
    zodExpression,
} from "./schema-to-zod";

const GENERATED =
    "/* @generated by pnpm contract - edit the Nest DTOs instead */";
const PATH_PARAM = /\{([^}]+)\}/g;
const JSON_MEDIA = "application/json";
const SUCCESS_STATUS = /^2\d\d$/;
const ENVELOPE_DATA = "data";
const UNKNOWN = "unknown";
const QUERY_LOCATION = "query";
const QUERY_ARGUMENT = "query";
const QUERY_HELPER = "queryString";
const QUERY_HELPER_MODULE = "@/lib/utils/query-string";

export const schemasFile = (schemas: Record<string, JsonSchema>): string => {
    const declarations = orderByDependency(schemas).flatMap((name) => [
        `export const ${schemaConstName(name)} = ${zodExpression(schemas[name])};`,
        `export type ${name} = z.infer<typeof ${schemaConstName(name)}>;`,
        "",
    ]);

    return [GENERATED, `import { z } from "zod";`, "", ...declarations].join(
        "\n",
    );
};

export const routeKey = (operationId: string): string => {
    const [controller, action] = operationId.split("_");
    const resource = controller.replace(/Controller$/, "");

    return `${resource[0].toLowerCase()}${resource.slice(1)}${action[0].toUpperCase()}${action.slice(1)}`;
};

export const responseDataSchema = (
    operation: Operation,
): JsonSchema | undefined => {
    const success = Object.entries(operation.responses ?? {}).find(([status]) =>
        SUCCESS_STATUS.test(status),
    );
    const schema = success?.[1].content?.[JSON_MEDIA]?.schema;

    if (!schema) return undefined;

    return (schema.allOf ?? [schema])
        .map((member) => member.properties?.[ENVELOPE_DATA])
        .find((data): data is JsonSchema => data !== undefined);
};

const queryType = (query: Parameter[]): string =>
    `{ ${query
        .map(
            ({ name, required, schema }) =>
                `${JSON.stringify(name)}${required ? "" : "?"}: ${schema ? typeExpression(schema) : UNKNOWN}`,
        )
        .join("; ")} }`;

const queryArgument = (query: Parameter[]): string[] =>
    query.length === 0
        ? []
        : [
              `${QUERY_ARGUMENT}${query.some(({ required }) => required) ? "" : "?"}: ${queryType(query)}`,
          ];

export const routeBuilder = (
    path: string,
    response = UNKNOWN,
    query: Parameter[] = [],
): string => {
    const params = [...path.matchAll(PATH_PARAM)].map((match) => match[1]);
    const brand = `as Endpoint<${response}>`;
    const signature = [
        ...params.map((name) => `${name}: string`),
        ...queryArgument(query),
    ].join(", ");

    if (signature === "") {
        return `() => ${JSON.stringify(path)} ${brand}`;
    }

    const template = path.replace(
        PATH_PARAM,
        (_, name: string) => `\${${name}}`,
    );
    const suffix =
        query.length === 0 ? "" : `\${${QUERY_HELPER}(${QUERY_ARGUMENT})}`;

    return `(${signature}) => \`${template}${suffix}\` ${brand}`;
};

export const routesFile = (paths: OpenApiDocument["paths"]): string => {
    const referenced = new Set<string>();
    let usesQuery = false;

    const entries = Object.entries(paths).flatMap(([path, operations]) =>
        Object.values(operations).flatMap((operation) => {
            if (!operation.operationId) return [];

            const data = responseDataSchema(operation);

            for (const name of data ? referencedSchemas(data) : []) {
                referenced.add(name);
            }

            const response = data ? typeExpression(data) : UNKNOWN;
            const query = (operation.parameters ?? []).filter(
                (parameter) => parameter.in === QUERY_LOCATION,
            );
            usesQuery ||= query.length > 0;

            return [
                `${routeKey(operation.operationId)}: ${routeBuilder(path, response, query)},`,
            ];
        }),
    );

    const helperImport = usesQuery
        ? [`import { ${QUERY_HELPER} } from "${QUERY_HELPER_MODULE}";`]
        : [];

    const schemaImport =
        referenced.size > 0
            ? [
                  `import type { ${[...referenced].sort().join(", ")} } from "./schemas";`,
              ]
            : [];

    return [
        GENERATED,
        `import type { Endpoint } from "@/lib/types/api";`,
        ...helperImport,
        ...schemaImport,
        "",
        "export const routes = {",
        ...entries,
        "} as const;",
        "",
    ].join("\n");
};
