import { JsonSchema, OpenApiDocument } from "./openapi-document";
import {
    orderByDependency,
    schemaConstName,
    zodExpression,
} from "./schema-to-zod";

const GENERATED =
    "/* @generated by pnpm contract - edit the Nest DTOs instead */";
const PATH_PARAM = /\{([^}]+)\}/g;

export const schemasFile = (schemas: Record<string, JsonSchema>): string => {
    const declarations = orderByDependency(schemas).flatMap((name) => [
        `export const ${schemaConstName(name)} = ${zodExpression(schemas[name])};`,
        `export type ${name} = z.infer<typeof ${schemaConstName(name)}>;`,
        "",
    ]);

    return [GENERATED, `import { z } from "zod";`, "", ...declarations].join(
        "\n",
    );
};

export const routeKey = (operationId: string): string => {
    const [controller, action] = operationId.split("_");
    const resource = controller.replace(/Controller$/, "");

    return `${resource[0].toLowerCase()}${resource.slice(1)}${action[0].toUpperCase()}${action.slice(1)}`;
};

export const routeBuilder = (path: string): string => {
    const params = [...path.matchAll(PATH_PARAM)].map((match) => match[1]);

    if (params.length === 0) return `() => ${JSON.stringify(path)}`;

    const template = path.replace(
        PATH_PARAM,
        (_, name: string) => `\${${name}}`,
    );
    const signature = params.map((name) => `${name}: string`).join(", ");

    return `(${signature}) => \`${template}\``;
};

export const routesFile = (paths: OpenApiDocument["paths"]): string => {
    const entries = Object.entries(paths).flatMap(([path, operations]) =>
        Object.values(operations).flatMap((operation) =>
            operation.operationId
                ? [`${routeKey(operation.operationId)}: ${routeBuilder(path)},`]
                : [],
        ),
    );

    return [
        GENERATED,
        "export const routes = {",
        ...entries,
        "} as const;",
        "",
    ].join("\n");
};
