const cardStyles = {
    orange: {
        border: "border-orange",
        text: "text-orange",
        light: "bg-orange",
        dark: "bg-dark-orange",
        shadow: "#592B0B",
        linear: "to-orange",
        fade: "#1C1615",
    },
    cyan: {
        border: "border-cyan",
        text: "text-cyan",
        light: "bg-cyan",
        dark: "bg-dark-cyan",
        shadow: "#005862",
        linear: "to-cyan",
        fade: "#051D27",
    },
    green: {
        border: "border-green",
        text: "text-green",
        light: "bg-green",
        dark: "bg-dark-green",
        shadow: "#06260F",
        linear: "to-green",
        fade: "#041616",
    },
    purple: {
        border: "border-purple",
        text: "text-purple",
        light: "bg-purple",
        dark: "bg-dark-purple",
        shadow: "#3B0040",
        linear: "to-purple",
        fade: "#190B27",
    },
    red: {
        border: "border-red",
        text: "text-red",
        light: "bg-red",
        dark: "bg-dark-red",
        shadow: "#400001",
        linear: "to-red",
        fade: "#1E0B12",
    },
    violet: {
        border: "border-violet",
        text: "text-violet",
        light: "bg-violet",
        dark: "bg-dark-violet",
        shadow: "#8B0090",
        linear: "to-violet",
        fade: "#0F1629",
    },
    ash: {
        border: "border-ash",
        text: "text-ash",
        light: "bg-ash",
        dark: "bg-dark-ash",
        shadow: "#8B0090",
        linear: "to-ash",
        fade: "#293544",
    },
    mauve: {
        border: "border-mauve",
        text: "text-mauve",
        light: "bg-mauve",
        dark: "bg-dark-mauve",
        shadow: "#8B0090",
        linear: "to-mauve",
        fade: "#1D1924",
    },
    pink: {
        border: "border-pink",
        text: "text-pink",
        light: "bg-pink",
        dark: "bg-dark-pink",
        shadow: "#8B0090",
        linear: "to-pink",
        fade: "#1C0E1E",
    },
    transparent: {
        border: "border-transparent",
        text: "text-transparent",
        light: "bg-transparent",
        dark: "",
        shadow: "",
        linear: "",
        fade: "",
    },
    yellow: {
        light: "bg-yellow",
        border: "border-yellow",
        text: "text-yellow",
        dark: "",
        shadow: "",
        linear: "to-yellow",
        fade: "#1D1F1B",
    },
    brown: {
        light: "bg-brown",
        border: "border-brown",
        text: "text-brown",
        dark: "",
        shadow: "",
        linear: "to-brown",
        fade: "#1D1F1B",
    },
    clay: {
        light: "bg-clay",
        border: "border-clay",
        text: "text-clay",
        dark: "",
        shadow: "",
        linear: "to-clay",
        fade: "#1D1F1B",
    },
     blue: {
        light: "bg-blue",
        border: "border-blue",
        text: "text-blue",
        dark: "",
        shadow: "",
        linear: "to-blue",
        fade: "#051428",
    },
};

export { cardStyles };
